# Use an official base image
FROM node:latest

# Set the working directory
WORKDIR /usr/src/app

# Copy the local source files to the container
COPY . .

# Set the command to run the JavaScript file
CMD ["node", "hello.js"]
